version: '3.9'

services:

    db:
        image: postgres:latest
        container_name: movie-db
        restart: always
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=movies
        ports:
            - '5432:5432'
    pgadmin:
        image: dpage/pgadmin4
        container_name: movie-admin
        restart: always
        ports:
            - "5050:80"
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: admin